#!/bin/sh

declare -a IPS=(
  {% for t in targets %}
  "{{ t.1 }}"
  {% endfor %}
)

declare -A NAMES=(
  {% for t in targets %}
  ["{{ t.1 }}"]="{{ t.0 }}"
  {% endfor %}
)

for IP in ${IPS[@]}; do
 ping -c 3 ${IP} > /dev/null
  if [ $? -eq 0 ]; then
    printf "[\033[1m\033[32m OK \033[0m] ping for \033[1m\033[33m%s\033[0m(IP: %s)\n" "${NAMES[$IP]}" "$IP"
  else
    printf "[\033[1m\033[31m NG \033[0m] ping for \033[1m\033[33m%s\033[0m(IP: %s)\n" "${NAMES[$IP]}" "$IP"
  fi
done
